### ISSUE TITLE
Adição de funcionalidades multi-usuário

### ISSUE THREAD

**Issue by vinivosh** [mm-projetos/Controle-de-Ambiente#3]
Sugestão: adicionar funcionalidades de multi-usuário no controlador, permitindo especificar permissões por usuário, e criando uma hierarquia de usuários. Pode ser extremamente útil em ambientes com uma variedade de permissões diferentes, como uma empresa.
Com essa adição, é necessário também um sistema de criação e gerenciamento dessas contas de usuários.

**Comment by YesterBolt** [comment]
Foi adicionada a função para que se possa haver múltiplos usuários. Agora cada usuário possui um "Grau" relacionado com cada casa. Podendo ser definido as funções permitidas de cada grau.
