### ISSUE TITLE
Funcionalidades de segurança domiciliar

### ISSUE THREAD

**Issue by vinivosh** [mm-projetos/Controle-de-Ambiente#4]
Sugestão: adicionar funcionalidades de segurança do ambiente ao sistema, como detecção de movimento por sensores, monitoramento por câmeras, entre outros.

**Comment by YesterBolt** [comment]
Achamos melhor colocar medidas de segurança como uma aplicação a parte, não se envolvendo em primeiro plano com o controle de ambiente. Porem acrescentamos a função para conseguir obter as imagens de câmera para ter um breve monitoramento.
