### ISSUE TITLE
Tratamento de comandos conflitantes

### ISSUE THREAD

**Issue by vinivosh** [mm-projetos/Controle-de-Ambiente#5]
É necessário especificar, nos casos de uso, (de maneira bem geral) o tratamento de comandos conflitantes do controlador, como, por exemplo, pedir para abrir uma porta já aberta, ou fechar um portão que já se encontra fechado.

**Comment by YesterBolt** [comment]
Realmente estão faltando os tratamentos de comandos conflitantes. Iremos analisar o modelo e fazer as devidas mudanças no caso de uso.

**Comment by YesterBolt** [comment]
Foram feitas as devidas atualizações no modelo de caso de uso.
