### ISSUE TITLE
Funcionalidades de notificação

### ISSUE THREAD

**Issue by vinivosh** [mm-projetos/Controle-de-Ambiente#6]
Sugestão: adicionar funcionalidades de notificações para eventos ocorridos no ambiente controlado, como por exemplo, ao alguém tocar a campainha, ou abrir o portão.

**Comment by YesterBolt** [comment]
Uma notificação ao usuário não faria parte do sistema visto que o mesmo seria voltado apenas para o controle do ambiente, mas estaremos discutindo mais sobre o assunto verificando se cabe mesmo essa função ao sistema

**Comment by YesterBolt** [comment]
Discutimos sobre a funcionalidade e chegamos a conclusão que haveriam uma grande quantidade de notificação no aplicativo, poluindo assim o mesmo.
