### ISSUE TITLE
Reescrever a especificação de requisitos

### ISSUE THREAD

**Issue by vinivosh** [mm-projetos/Controle-de-Ambiente#7]
Na documentação dos casos de uso, a especificação dos requisitos deveria ser reescrita para condizer mais com sua função formal. Os requisitos não podem se assemelhar a uma "sequência de passos", pois isso é adequado nos casos de uso em si.
É importante que os casos de uso derivem-se das especificações de requisitos.

**Comment by YesterBolt** [comment]
De fato concordamos com estas mudanças. Estaremos realizando mudanças no caso de uso, em específico a parte de requisitos.

**Comment by YesterBolt** [comment]
O modelo de caso de uso foi atualizado com as devidas mudanças.
